# Generated by Django 2.2.4 on 2019-08-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190824_1403'),
        ('blog', '0002_auto_20190828_0606'),
    ]

    operations = [
    ]
